const cnst = {}

const CODE_COMM_0_SUCCESS = 0;
cnst.CODE_COMM_0_SUCCESS = CODE_COMM_0_SUCCESS;

const CODE_COMM_GRANT_EXPIRED = 21;
cnst.CODE_COMM_GRANT_EXPIRED = CODE_COMM_GRANT_EXPIRED;

const CODE_COMM_INPUT_ERROR = 70;
cnst.CODE_COMM_INPUT_ERROR = CODE_COMM_INPUT_ERROR;

const COMMODITY_STATUS_ON_SALE = 30;
cnst.COMMODITY_STATUS_ON_SALE = COMMODITY_STATUS_ON_SALE;

const COUNT_FLOOR_COMMODITY = 8;
cnst.COUNT_FLOOR_COMMODITY = COUNT_FLOOR_COMMODITY;

const ID_TOP_REGION = '8';
cnst.ID_TOP_REGION = ID_TOP_REGION;

const HQ_ID = "8";
cnst.ID_HQ = HQ_ID;

const HQ_NAME = "深圳市柏君科技有限公司";
cnst.NAME_HQ = HQ_NAME;

const MALL_TYPE_G_B2B = 1;
cnst.MALL_TYPE_G_B2B = MALL_TYPE_G_B2B;

const MALL_TYPE_G_B2C = 3;
cnst.MALL_TYPE_G_B2C = MALL_TYPE_G_B2C;

const MALL_TYPE_R_B2B = 5;
cnst.MALL_TYPE_R_B2B = MALL_TYPE_R_B2B;

const MALL_TYPE_R_B2C = 7;
cnst.MALL_TYPE_R_B2C = MALL_TYPE_R_B2C;

const MENU_MENU_SP_B2B_G = 1;
cnst.MENU_SP_G_B2B = MENU_MENU_SP_B2B_G;

const MENU_MENU_SP_B2B_R = 3;
cnst.MENU_SP_R_B2B = MENU_MENU_SP_B2B_R;

const MENU_MENU_SP_B2C_G = 5;
cnst.MENU_SP_G_B2C = MENU_MENU_SP_B2C_G;

const MENU_MENU_SP_B2C_R = 7;
cnst.MENU_SP_R_B2C = MENU_MENU_SP_B2C_R;

const MENU_HQ_B2B_G = 9;
cnst.MENU_HQ_G_B2B = MENU_HQ_B2B_G;

const MENU_HQ_B2B_R = 11;
cnst.MENU_HQ_R_B2B = MENU_HQ_B2B_R;

const MENU_HQ_B2C_G = 13;
cnst.MENU_HQ_G_B2C = MENU_HQ_B2C_G;

const MENU_HQ_B2C_R = 15;
cnst.MENU_HQ_R_B2C = MENU_HQ_B2C_R;

const MENU_OP_B2B_G = 17;
cnst.MENU_OP_G_B2B = MENU_OP_B2B_G;

const MENU_OP_B2B_R = 19;
cnst.MENU_OP_R_B2B = MENU_OP_B2B_R;

const MENU_OP_B2C_G = 21;
cnst.MENU_OP_G_B2C = MENU_OP_B2C_G;

const MENU_OP_B2C_R = 23;
cnst.MENU_OP_R_B2C = MENU_OP_B2C_R;

const MENU_SS_B2B_G = 25;
cnst.MENU_SS_G_B2B = MENU_SS_B2B_G;

const MENU_SS_B2B_R = 27;
cnst.MENU_SS_R_B2B = MENU_SS_B2B_R;

const MENU_SS_B2C_G = 29;
cnst.MENU_SS_G_B2C = MENU_SS_B2C_G;

const MENU_SS_B2C_R = 31;
cnst.MENU_SS_R_B2C = MENU_SS_B2C_R;

const MENU_MB_B2B_G = 33;
cnst.MENU_MB_G_B2B = MENU_MB_B2B_G;

const MENU_MB_B2B_R = 35;
cnst.MENU_MB_R_B2B = MENU_MB_B2B_R;

const MENU_MB_B2C_G = 37;
cnst.MENU_MB_G_B2C = MENU_MB_B2C_G;

const MENU_MB_B2C_R = 39;
cnst.MENU_MB_R_B2C = MENU_MB_B2C_R;

const MENU_SHOW_ALL_OP = 41;
cnst.MENU_SHOW_ALL_OP = MENU_SHOW_ALL_OP;

const NO_ID = "-1";
cnst.ID_NO = NO_ID;

const ORG_TYPE_OP = 9;
cnst.ORG_TYPE_OP = ORG_TYPE_OP;

const ORG_TYPE_SP_G = 1;
cnst.ORG_TYPE_SP_G = ORG_TYPE_SP_G;

const ORG_TYPE_SP_R = 3;
cnst.ORG_TYPE_SP_R = ORG_TYPE_SP_R;

const ORG_TYPE_SS = 11;
cnst.ORG_TYPE_SS = ORG_TYPE_SS;

const PAGE_SIZE = 30;
cnst.PAGE_SIZE = PAGE_SIZE;

const PAY_TYPE_ONLINE = 1;
cnst.PAY_TYPE_ONLINE = PAY_TYPE_ONLINE;

const PAY_TYPE_OFFLINE = 3;
cnst.PAY_TYPE_OFFLINE = PAY_TYPE_OFFLINE;

const PAY_TYPE_BOTH = 5;
cnst.PAY_TYPE_BOTH = PAY_TYPE_BOTH;

const REQUEST_TYPE_WWW = 'application/x-www-form-urlencoded';
cnst.REQUEST_TYPE_WWW = REQUEST_TYPE_WWW;

const SHOW_TYPE_FLOOR = 1;
cnst.SHOW_TYPE_FLOOR = SHOW_TYPE_FLOOR;

const SHOW_TYPE_CAROUSEL = 3;
cnst.SHOW_TYPE_CAROUSEL = SHOW_TYPE_CAROUSEL;

const SHOW_TYPE_FEATURE = 5;
cnst.SHOW_TYPE_FEATURE = SHOW_TYPE_FEATURE;

const STATUS_NEW = 1;
cnst.STATUS_NEW = STATUS_NEW;

const STATUS_PROCESS3 = 3;
cnst.STATUS_PROCESS3 = STATUS_PROCESS3;

const STATUS_PROCESS5 = 5;
cnst.STATUS_PROCESS5 = STATUS_PROCESS5;

const STATUS_ACTIVE = 7;
cnst.STATUS_ACTIVE = STATUS_ACTIVE;

const STATUS_PROCESS9 = 9;
cnst.STATUS_PROCESS9 = STATUS_PROCESS9;

const STATUS_FINISHED = 10;
cnst.STATUS_FINISHED = STATUS_FINISHED;

const TRADE_TYPE_GROUPON = 5;
cnst.TRADE_TYPE_GROUPON = TRADE_TYPE_GROUPON;

export default cnst;


